.TH "kitten-desktop-ui-set-accent-color" "1" "Jul 14, 2025" "0.42.1" "kitten Manual"
.SH Name
kitten-desktop-ui-set-accent-color \- Change the accent color
.SH Usage
.SY "kitten desktop-ui set-accent-color  color_as_hex_or_name"
.YS
.SH Options
.TP
.BI "--help, -h" " [=no]"
Show help for this command
