.TH "kitten-@-load-config" "1" "Nov 03, 2025" "0.44.0" "kitten Manual"
.SH Name
kitten-@-load-config \- (Re)load a config file
.SH Usage
.SY "kitten @ load-config  CONF_FILE ..."
.YS
.SH Description
(Re)load the specified kitty.conf config files(s). If no files are specified the previously specified config file is reloaded. Note that the specified paths must exist and be readable by the kitty process on the computer that process is running on. Relative paths are resolved with respect to the kitty config directory on the computer running kitty.
.SH Options
.TP
.BI "--ignore-overrides" " [=no]"
By default, any config overrides previously specified at the kitty invocation command line or a previous load\-config\-file command are respected. Use this option to have them ignored instead.
.TP
.BI "--override, -o" 
Override individual configuration options, can be specified multiple times. Syntax: name=value. For example: 
.B \-o font_size=20
.TP
.BI "--no-response" " [=no]"
Don\[aq]t wait for a response indicating the success of the action. Note that using this option means that you will not be notified of failures.
.TP
.BI "--help, -h" " [=no]"
Show help for this command
.SH Global options
.TP
.BI "--to" 
An address for the kitty instance to control. Corresponds to the address given to the kitty instance via the 
.B \-\-listen\-on option or the 
.B listen_on setting in 
.I kitty.conf. If not specified, the environment variable 
.B KITTY_LISTEN_ON is checked. If that is also not found, messages are sent to the controlling terminal for this process, i.e. they will only work if this process is run within a kitty window.
.TP
.BI "--password" 
A password to use when contacting kitty. This will cause kitty to ask the user for permission to perform the specified action, unless the password has been accepted before or is pre\-configured in 
.I kitty.conf. To use a blank password specify 
.B \-\-use\-password as always.
.TP
.BI "--password-file" " [=rc\-pass]"
A file from which to read the password. Trailing whitespace is ignored. Relative paths are resolved from the kitty configuration directory. Use \- to read from STDIN. Use fd:num to read from the file descriptor num. Used if no 
.B \-\-password is supplied. Defaults to checking for the 
.I rc\-pass file in the kitty configuration directory.
.TP
.BI "--password-env" " [=KITTY_RC_PASSWORD]"
The name of an environment variable to read the password from. Used if no 
.B \-\-password\-file is supplied. Defaults to checking the environment variable 
.B KITTY_RC_PASSWORD.
.TP
.BI "--use-password" " [=if\-available]"
If no password is available, kitty will usually just send the remote control command without a password. This option can be used to force it to always or never use the supplied password. If set to always and no password is provided, the blank password is used.

Choices: if-available, always, never
