.TH "kitten-desktop-ui-set-contrast" "1" "Jul 14, 2025" "0.42.1" "kitten Manual"
.SH Name
kitten-desktop-ui-set-contrast \- Change the contrast. Can be high or normal.
.SH Usage
.SY "kitten desktop-ui set-contrast  high|normal"
.YS
.SH Options
.TP
.BI "--help, -h" " [=no]"
Show help for this command
