.TH "kitten-@-run" "1" "Nov 03, 2025" "0.44.0" "kitten Manual"
.SH Name
kitten-@-run \- Run a program on the computer in which kitty is running and get the output
.SH Usage
.SY "kitten @ run  CMD ..."
.YS
.SH Description
Run the specified program on the computer in which kitty is running. When STDIN is not a TTY it is forwarded to the program as its STDIN. STDOUT and STDERR from the the program are forwarded here. The exit status of this invocation will be the exit status of the executed program. If you wish to just run a program without waiting for a response,  use @ launch \-\-type=background instead.
.SH Options
.TP
.BI "--env" 
Environment variables to set in the child process. Can be specified multiple times to set different environment variables. Syntax: name=value. Using name= will set to empty string and just name will remove the environment variable.
.TP
.BI "--allow-remote-control" " [=no]"
The executed program will have privileges to run remote control commands in kitty.
.TP
.BI "--remote-control-password" 
Restrict the actions remote control is allowed to take. This works like 
.B remote_control_password. You can specify a password and list of actions just as for 
.B remote_control_password. For example::


    \-\-remote\-control\-password \[aq]\[dq]my passphrase\[dq] get\-* set\-colors\[aq]

This password will be in effect for this window only. Note that any passwords you have defined for 
.B remote_control_password in 
.I kitty.conf are also in effect. You can override them by using the same password here. You can also disable all 
.B remote_control_password global passwords for this window, by using::


    \-\-remote\-control\-password \[aq]!\[aq]

This option only takes effect if 
.B \-\-allow\-remote\-control is also specified. Can be specified multiple times to create multiple passwords. This option was added to kitty in version 0.26.0
.TP
.BI "--help, -h" " [=no]"
Show help for this command
.SH Global options
.TP
.BI "--to" 
An address for the kitty instance to control. Corresponds to the address given to the kitty instance via the 
.B \-\-listen\-on option or the 
.B listen_on setting in 
.I kitty.conf. If not specified, the environment variable 
.B KITTY_LISTEN_ON is checked. If that is also not found, messages are sent to the controlling terminal for this process, i.e. they will only work if this process is run within a kitty window.
.TP
.BI "--password" 
A password to use when contacting kitty. This will cause kitty to ask the user for permission to perform the specified action, unless the password has been accepted before or is pre\-configured in 
.I kitty.conf. To use a blank password specify 
.B \-\-use\-password as always.
.TP
.BI "--password-file" " [=rc\-pass]"
A file from which to read the password. Trailing whitespace is ignored. Relative paths are resolved from the kitty configuration directory. Use \- to read from STDIN. Use fd:num to read from the file descriptor num. Used if no 
.B \-\-password is supplied. Defaults to checking for the 
.I rc\-pass file in the kitty configuration directory.
.TP
.BI "--password-env" " [=KITTY_RC_PASSWORD]"
The name of an environment variable to read the password from. Used if no 
.B \-\-password\-file is supplied. Defaults to checking the environment variable 
.B KITTY_RC_PASSWORD.
.TP
.BI "--use-password" " [=if\-available]"
If no password is available, kitty will usually just send the remote control command without a password. This option can be used to force it to always or never use the supplied password. If set to always and no password is provided, the blank password is used.

Choices: if-available, always, never
