.TH "kitten-desktop-ui-set-color-scheme" "1" "Jul 14, 2025" "0.42.1" "kitten Manual"
.SH Name
kitten-desktop-ui-set-color-scheme \- Change the color scheme
.SH Usage
.SY "kitten desktop-ui set-color-scheme  light|dark|no-preference|toggle"
.YS
.SH Options
.TP
.BI "--help, -h" " [=no]"
Show help for this command
