.TH "kitten" "1" "Nov 03, 2025" "0.44.0" "kitten Manual"
.SH Name
kitten \- Fast, statically compiled implementations of various kittens (command line tools for use with kitty)
.SH Usage
.SY "kitten command [command options] [command args]"
.YS
.SH Description
kitten serves as a launcher for running individual kittens. Each kitten can be run as kitten command. The list of available kittens is given below.
.SH Commands
.TP 2
@
Control kitty remotely. See: 
.MR kitten-@ 1
.TP 2
ask
Ask the user for input. See: 
.MR kitten-ask 1
.TP 2
choose-files
Choose files, fast. See: 
.MR kitten-choose-files 1
.TP 2
choose-fonts
Choose the fonts used in kitty. See: 
.MR kitten-choose-fonts 1
.TP 2
clipboard
Copy/paste with the system clipboard, even over SSH. See: 
.MR kitten-clipboard 1
.TP 2
desktop-ui
Implement various desktop components for use with lightweight compositors/window managers on Linux. See: 
.MR kitten-desktop-ui 1
.TP 2
diff
Pretty, side\-by\-side diffing of files and images. See: 
.MR kitten-diff 1
.TP 2
edit-in-kitty
Edit a file in a kitty overlay window. See: 
.MR kitten-edit-in-kitty 1
.TP 2
hints
Select text from screen with keyboard. See: 
.MR kitten-hints 1
.TP 2
hyperlinked-grep
Add hyperlinks to the output of ripgrep. See: 
.MR kitten-hyperlinked-grep 1
.TP 2
icat
Display images in the terminal. See: 
.MR kitten-icat 1
.TP 2
mouse-demo
Demo the mouse handling kitty implements for terminal programs. See: 
.MR kitten-mouse-demo 1
.TP 2
notify
Send notifications to the user. See: 
.MR kitten-notify 1
.TP 2
panel
Use a command line program to draw a GPU accelerated panel on your desktop. See: 
.MR kitten-panel 1
.TP 2
query-terminal
Query the terminal for various capabilities. See: 
.MR kitten-query-terminal 1
.TP 2
quick-access-terminal
A quick access terminal window that you can bring up instantly with a keypress or a command.. See: 
.MR kitten-quick-access-terminal 1
.TP 2
run-shell
Run the user\[aq]s shell with shell integration enabled. See: 
.MR kitten-run-shell 1
.TP 2
show-key
Show the codes generated by the terminal for key presses in various keyboard modes. See: 
.MR kitten-show-key 1
.TP 2
ssh
Truly convenient SSH. See: 
.MR kitten-ssh 1
.TP 2
themes
Manage kitty color schemes easily. See: 
.MR kitten-themes 1
.TP 2
transfer
Transfer files easily over the TTY device. See: 
.MR kitten-transfer 1
.TP 2
unicode-input
Browse and select unicode characters by name. See: 
.MR kitten-unicode-input 1
.TP 2
update-self
Update this kitten binary. See: 
.MR kitten-update-self 1
.PP
Get help for an individual command by running:
.SY kitten
command -h
.YS
.SH Options
.TP
.BI "--version" " [=no]"
The current kitten version.
.TP
.BI "--help, -h" " [=no]"
Show help for this command
